### ISSUE TITLE
模拟器朋友圈不支持图片选择

### ISSUE THREAD

**Issue by gyyxiaogao** [iotjin/jh_flutter_demo#10]

**Comment by iotjin** [comment]
朋友圈只写了选择器，没有加选择图片功能，demo列表里有图片选择的功能

**Comment by gyyxiaogao** [comment]
![图片](https://user-images.githubusercontent.com/16957066/102863481-9cef8900-446d-11eb-8fd4-96ccb628690c.png)
选择图片后为啥没有预览功能,这块判断是不是要优化一下?
<img width="386" alt="图片" src="https://user-images.githubusercontent.com/16957066/102864021-6d8d4c00-446e-11eb-9ded-30c1e0a8a3c1.png"> 从相册中选出来的图片是Asset类型

**Comment by gyyxiaogao** [comment]
还有一个问题,不能设置最多多少张图片
![图片](https://user-images.githubusercontent.com/16957066/102868112-bc3de480-4474-11eb-8046-cd4f3a4c86bf.png)
![图片](https://user-images.githubusercontent.com/16957066/102868157-cc55c400-4474-11eb-827c-eee7bd1ac773.png)
