### ISSUE TITLE
还有一个问题,不能设置最多多少张图片

### ISSUE THREAD

**Issue by gyyxiaogao** [iotjin/jh_flutter_demo#11]
还有一个问题,不能设置最多多少张图片
![图片](https://user-images.githubusercontent.com/16957066/102868112-bc3de480-4474-11eb-8046-cd4f3a4c86bf.png)
![图片](https://user-images.githubusercontent.com/16957066/102868157-cc55c400-4474-11eb-827c-eee7bd1ac773.png)

_Originally posted by @gyyxiaogao in https://github.com/iotjin/jh_flutter_demo/issues/10#issuecomment-749421575_

**Comment by iotjin** [comment]
现在默认最多选9张，如果进入相册选择界面，显示的是还可以选择几张，你已经选了3张，还可以选6张，相册界面没有选中，显示的是0
