### ISSUE TITLE
![图片](https://user-images.githubusercontent.com/16957066/102863481-9cef8900-446d-11eb-8fd4-96ccb628690c.png)

### ISSUE THREAD

**Issue by gyyxiaogao** [iotjin/jh_flutter_demo#12]
![图片](https://user-images.githubusercontent.com/16957066/102863481-9cef8900-446d-11eb-8fd4-96ccb628690c.png)
选择图片后为啥没有预览功能,这块判断是不是要优化一下?
<img width="386" alt="图片" src="https://user-images.githubusercontent.com/16957066/102864021-6d8d4c00-446e-11eb-9ded-30c1e0a8a3c1.png"> 从相册中选出来的图片是Asset类型

_Originally posted by @gyyxiaogao in https://github.com/iotjin/jh_flutter_demo/issues/10#issuecomment-749403383_

**Comment by iotjin** [comment]
项目中有图片浏览的demo，只是选择图片这里没有加预览功能，选完图片是返回的包含图片路径的数组

**Comment by iotjin** [comment]
> ![图片](https://user-images.githubusercontent.com/16957066/102863481-9cef8900-446d-11eb-8fd4-96ccb628690c.png)
> 选择图片后为啥没有预览功能,这块判断是不是要优化一下?
> <img alt="图片" width="386" src="https://user-images.githubusercontent.com/16957066/102864021-6d8d4c00-446e-11eb-9ded-30c1e0a8a3c1.png"> 从相册中选出来的图片是Asset类型
> 
> _Originally posted by @gyyxiaogao in [#10 (comment)](https://github.com/iotjin/jh_flutter_demo/issues/10#issuecomment-749403383)_



> ![图片](https://user-images.githubusercontent.com/16957066/102863481-9cef8900-446d-11eb-8fd4-96ccb628690c.png)
> 选择图片后为啥没有预览功能,这块判断是不是要优化一下?
> <img alt="图片" width="386" src="https://user-images.githubusercontent.com/16957066/102864021-6d8d4c00-446e-11eb-9ded-30c1e0a8a3c1.png"> 从相册中选出来的图片是Asset类型
> 
> _Originally posted by @gyyxiaogao in [#10 (comment)](https://github.com/iotjin/jh_flutter_demo/issues/10#issuecomment-749403383)_

刚刚我把查看图片添加到选择图片的demo里了
