### ISSUE TITLE
登录时显示接口异常，请帮忙看下。

### ISSUE THREAD

**Issue by cheshuangchun** [iotjin/jh_flutter_demo#13]
打印日志如下:

Performing hot restart...
Syncing files to device iPhone X...
Restarted application in 1,034ms.
flutter: iOS
flutter: name =jin
flutter: pwd =123456
flutter: 接口请求异常： code: 1004, msg: 连接超时！

**Comment by iotjin** [comment]
你是不是没有网？登录不上你去掉网络请求直接登录也行啊

**Comment by cheshuangchun** [comment]
嗯，已经直接进去了
