### ISSUE TITLE
JhCascadeTreePicker树选择器中当treeData只有一个根结点时，始终选择不了，也就是无效

### ISSUE THREAD

**Issue by HongXiXi** [iotjin/jh_flutter_demo#18]
JhCascadeTreePicker.show(context,
                        data: treeData,
                        // labelKey: 'name',
                        // valueKey: 'id',
                        title: '请选择类型',
                        splitString: ' / ',
                        clickCallBack: (selectItem, selectArr) {
                      print(selectItem);
                      print(selectArr);
                    });

**Comment by HongXiXi** [comment]
final treeData = [
    {
      'value': 'zhinan',
      'label': '指南',
      'children': [
        {
          'value': 'shejiyuanze',
          'label': '设计原则',
          'children': [
            {'value': 'yizhi', 'label': '一致'},
            {'value': 'fankui', 'label': '反馈'},
            {'value': 'xiaolv', 'label': '效率'},
            {'value': 'kekong', 'label': '可控'}
          ]
        },
        {
          'value': 'daohang',
          'label': '导航',
          'children': [
            {'value': 'cexiangdaohang2', 'label': '侧向导航'},
            {'value': 'dingbudaohang2', 'label': '顶部导航'}
          ]
        }
      ]
    }
  ];

**Comment by iotjin** [comment]
已修复
