### ISSUE TITLE
vscode签入后无法调试运行

### ISSUE THREAD

**Issue by EricShen-ESStudio** [iotjin/jh_flutter_demo#19]
签入后用vscode打开，flutter pub get
之后运行安卓虚拟器，一直提示Launching lib\main.dart on sdk gphone x86 64 arm64 in debug mode...

请问是什么原因？

**Comment by iotjin** [comment]
能否发下完整报错提示和你的开发环境，是一直卡到这里无法安装？还是有其他报错信息，你可以先换真机试试看是不是模拟器的问题
