### ISSUE TITLE
扫码页面问题

### ISSUE THREAD

**Issue by HongXiXi** [iotjin/jh_flutter_demo#20]
首页，右上角+号，扫一扫的扫码页面，非要点击框外任意处才能拍到东西，否则只有框框和文字，背后一片黑暗。
![微信图片_20230410155625](https://user-images.githubusercontent.com/121912613/230855404-d914cf2d-fcf4-4dfa-a459-e9690adbeca1.jpg)

**Comment by iotjin** [comment]
你的开发环境和设备信息？我需要一个可复现的环境，我这边的真机和模拟器都无法复现

**Comment by HongXiXi** [comment]
小米11，模拟器上也是一样的。奇怪，为何你那边全是好的 :(

**Comment by iotjin** [comment]
你连着你的设备，`flutter doctor -v` 发下你的开发环境，可以的话把你操作录个屏

**Comment by HongXiXi** [comment]
![flutterdoctor](https://user-images.githubusercontent.com/121912613/232988113-cde3040c-0df3-4aad-8127-de208f3f1b55.png)
[录像4.zip](https://github.com/iotjin/jh_flutter_demo/files/11269510/4.zip)

好的，请查看录屏

**Comment by iotjin** [comment]
已修复，我看你的环境是3.3.9，好像是在3.7.0以下的版本有这种问题，参考https://github.com/juliuscanute/qr_code_scanner/issues/550
