### ISSUE TITLE
Git error. Command: `git clone --mirror https://github.com/sirkalmi/flutter_echarts.git

### ISSUE THREAD

**Issue by JasonYinH** [iotjin/jh_flutter_demo#22]
![image](https://github.com/iotjin/jh_flutter_demo/assets/40187930/3ddc7164-de1e-483a-a777-10512f6aeabd)

**Comment by JasonYinH** [comment]
![image](https://github.com/iotjin/jh_flutter_demo/assets/40187930/5d865f52-0767-4ca3-a002-074793aaeb2d)
版本问题吗
flutter 3.13.7

**Comment by JasonYinH** [comment]
# 拍照与录像(微信UI) https://pub.flutter-io.cn/packages/wechat_camera_picker
  wechat_camera_picker: ^4.0.2
这个还要升级要不然报错
![image](https://github.com/iotjin/jh_flutter_demo/assets/40187930/0f53ee78-d9d2-4441-8e66-939e93b8759c)

**Comment by JasonYinH** [comment]
![image](https://github.com/iotjin/jh_flutter_demo/assets/40187930/0dfb1c50-dfd6-477b-943e-456b041b115c)
xiuga修改以上几个地方，终于可以运行起来了
![0175B177](https://github.com/iotjin/jh_flutter_demo/assets/40187930/c0240307-e405-4fb8-8d08-83566caa39c4)

**Comment by iotjin** [comment]
![image](https://github.com/iotjin/jh_flutter_demo/assets/9895575/23798200-880d-45ea-be21-6f4293d522cd)
这是项目运行环境，按这个来，另外flutter_echarts应该是github访问的问题
