### ISSUE TITLE
登录一直加载中

### ISSUE THREAD

**Issue by JasonYinH** [iotjin/jh_flutter_demo#23]
![image](https://github.com/iotjin/jh_flutter_demo/assets/40187930/9396eee7-1594-471c-9624-7493e5855f34)

**Comment by JasonYinH** [comment]
为啥域名没有呢，运行demo
![image](https://github.com/iotjin/jh_flutter_demo/assets/40187930/6de63524-322f-4826-b95b-7ef76c075b71)

**Comment by JasonYinH** [comment]
https://iotjin.github.io/jh_flutter_demo/#/home这个正常

**Comment by iotjin** [comment]
![image](https://github.com/iotjin/jh_flutter_demo/assets/9895575/dc4a66f3-33e4-4953-ac04-4be73ef65b3d)

你按这个运行环境来，域名是因为没有加到打印里，你想看的话加上APIs.apiPrefix就有了啊
