### ISSUE TITLE
went wrong

### ISSUE THREAD

**Issue by 863111500** [iotjin/jh_flutter_demo#28]
* What went wrong:
Could not open settings generic class cache for settings file 'D:\xxxx\code\flutter\jh_flutter_demo\android\settings.gradle' (C:\Users\xxxx\.gradle\caches\7.0.2\scripts\9ro1u0k9hdyieqwldgdt37f3r).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 61

**Comment by iotjin** [comment]
The log information shows that you are using java17, change it to java11, and clear gradle to recompile and run
