### ISSUE TITLE
flutter_picker error

### ISSUE THREAD

**Issue by 2547409617** [iotjin/jh_flutter_demo#29]
请问这是什么问题？新人求助

Flutter (Channel stable, 3.22.2

flutter_picker-2.1.0/lib/picker.dart:429:31: Error: The getter 'bottomAppBarColor' isn't defined for the class 'ThemeData'.

**Comment by iotjin** [comment]
你开发环境和代码的不一致吧
![image](https://github.com/iotjin/jh_flutter_demo/assets/9895575/a4943adc-4688-4b32-9def-0946ce61b223)
