### ISSUE TITLE
iOS 设备跑起来报错

### ISSUE THREAD

**Issue by liubitaoHaylou** [iotjin/jh_flutter_demo#30]
报错信息如下：
(lldb) 2024-08-29 15:38:29.067198+0800 Runner[67482:9302572] [ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000000000000
error: memory read failed for 0x0
Target 0: (Runner) stopped.

**Comment by iotjin** [comment]
你检查一下环境和项目环境是否一样，我这边试了一下可以正常运行。不过也有这个错误提示，这个提示`flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.`可以通过修改info.plist 里的 FLTEnableImpeller 为 false解决
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	...//省略代码
	<key>FLTEnableImpeller</key>
    <false/>
	...//省略代码
</dict>
</plist>
```

**Comment by iotjin** [comment]
[✓] Flutter (Channel stable, 3.16.0, on macOS 13.0 22A380 darwin-arm64, locale zh-Hans-TW)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)

**Comment by liubitaoHaylou** [comment]
当我使用18.0的iphone11手机是可以运行的， 但是使用16.7.8的iphone x手机时就报错了
![image](https://github.com/user-attachments/assets/1faab840-389b-4107-b3b0-a5b3ef8ca34a)

**Comment by iotjin** [comment]
我这可能是xcode版本低吧，没复现，看着应该是`connectivity_plus`有问题，我搜了一下 issue， [connectivity_plus crashes when running on real IOS device ](https://github.com/fluttercommunity/plus_plugins/issues/2155)，你可以更新connectivity_plus版本和iOS中的Podfile为12试试看
