### ISSUE TITLE
Undefined class 'Router'. Try changing the name to the name of an existing class, or creating a class with the name 'Router'.

### ISSUE THREAD

**Issue by MichaelShuai** [iotjin/jh_flutter_demo#4]
Undefined class 'Router'.
Try changing the name to the name of an existing class, or creating a class with the name 'Router'.
这个Router找不到。什么情况

**Comment by qianshang** [comment]
替换成 FluroRouter
https://pub.flutter-io.cn/packages/fluro

**Comment by iotjin** [comment]
fluro已升级适配（1.7.7）
